### PR TITLE
Feature/svelte kit v0.463

### PR DESCRIPTION
**Pull request by UltraCakeBakery**
Changes:
- updated svelte-kit
- renamed some directories
- moved some components 
- updated blog posts (code, not content) to get rid of warnings
- removed wrapping <div> to make the page structure easier to deal with

And some more changes. Please read the individual texts for each commit.

### CODE REVIEW

**Comment by UltraCakeBakery** [comment]
@justingolden21 this now includes #22

**Comment by justingolden21** [comment]
Awesome will check, thanks!

**Comment by UltraCakeBakery** [comment]
Test

**Comment by UltraCakeBakery** [comment]
What branches are blocking this branch?

**Pull request merged**
